export const calenderData = [
  {
    shipClass: 'Fighter',
    coreType: 'Fission',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Tank',
    coreType: 'Plasma',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Mining',
    coreType: 'Mechanical',
    shipID: 9177,
    level: 5,
    rarity: 1,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 4,
    rarity: 3,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 5,
    rarity: 4,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Support',
    coreType: 'Magnetic',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 4,
    rarity: 3,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 5,
    rarity: 4,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Fighter',
    coreType: 'TWTR',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
  {
    shipClass: 'Support',
    coreType: 'Magnetic',
    shipID: 9177,
    level: 5,
    rarity: 2,
    pricedps: '$452.85',
    shipstat: true,
  },
]
